spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hdurmaz
    password: hdurmaz
    username: hdurmaz
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect